language: python

python:
    - 2.6
    - 2.7
    - 3.3
    - 3.4

before_install:
  - pip list

install:
  # install deps
  - pip install -r requirements.txt
  - pip install python-coveralls

script:
  - py.test --cov-report term-missing --cov-config .coveragerc --cov=citools

after_success:
  - coveralls
  - ls -la
