language: python

python:
    - 2.7
    - 3.3
    - 3.4

before_install:
  - pip list

install:
  # install deps
  - pip install -r requirements.txt

script:
  - nosetests

after_script:
  - echo "install"