RESPONSE = {
    u'actions':
        [{u'causes': [{u'shortDescription': u'commit notification 9e29a0ebd00a8515ab6d2fa9c6b2bef4569aa4aa'}]},
         {},
         {u'parameters': []},
         {},
         {u'buildsByBranchName': {
             u'origin/master': {u'buildNumber': 1375,
                                u'buildResult': None,
                                u'marked': {u'SHA1': u'9e29a0ebd00a8515ab6d2fa9c6b2bef4569aa4aa',
                                            u'branch': [{u'SHA1': u'9e29a0ebd00a8515ab6d2fa9c6b2bef4569aa4aa',
                                                         u'name': u'origin/master'}]},
                                u'revision': {u'SHA1': u'9e29a0ebd00a8515ab6d2fa9c6b2bef4569aa4aa',
                                              u'branch': [{u'SHA1': u'9e29a0ebd00a8515ab6d2fa9c6b2bef4569aa4aa',
                                                           u'name': u'origin/master'}]}},
             u'lastBuiltRevision': {u'SHA1': u'9e29a0ebd00a8515ab6d2fa9c6b2bef4569aa4aa',
                                    u'branch': [{u'SHA1': u'9e29a0ebd00a8515ab6d2fa9c6b2bef4569aa4aa',
                                                 u'name': u'origin/master'}]},
             u'remoteUrls': [u'ssh://repo.org/group/repo.git'],
             u'scmName': u''},
         },
         {},
         {u'failCount': 0,
          u'skipCount': 2,
          u'totalCount': 171,
          u'urlName': u'testReport'},
         {},
         {},
         {},
         {}],
    u'artifacts': [],
    u'building': False,
    u'builtOn': u'',
    u'changeSet': {u'items': [{u'affectedPaths': [u'project/source/source.py',
                                                  u'project/config.txt'],
                               u'author': {u'absoluteUrl': u'http://jenkins.org/user/dan.developer',
                                           u'fullName': u'dan.developer'},
                               u'comment': u'updated configuration\n',
                               u'commitId': u'36f9c011124a1ee8d4ff26970aa6c06bc237ecdb',
                               u'date': u'2015-09-17 15:55:44 +0200',
                               u'id': u'36f9c011124a1ee8d4ff26970aa6c06bc237ecdb',
                               u'msg': u'updated configuration',
                               u'paths': [{u'editType': u'edit',
                                           u'file': u'project/source/source.py'},
                                          {u'editType': u'edit', u'file': u'project/config.txt'}],
                               u'timestamp': -1}],
                   u'kind': u'git'},
    u'culprits': [{u'absoluteUrl': u'http://jenkins.org/user/dan.developer',
                   u'fullName': u'dan.developer'}],
    u'description': None,
    u'displayName': u'#1375',
    u'duration': 6555,
    u'estimatedDuration': 9469,
    u'executor': None,
    u'fullDisplayName': u'master #575',
    u'id': u'1375',
    u'keepLog': False,
    u'number': 575,
    u'queueId': 803,
    u'result': u'SUCCESS',
    u'timestamp': 1442498211077,
    u'url': u'http://jenkins.org/job/master/575/'}
