#!/usr/bin/env python
from optparse import OptionParser
import os
import shelve
from junit_xml import TestSuite

if __name__ == '__main__':

    parser = OptionParser()

    (options, args) = parser.parse_args()

    if len(args) == 1:
        target = args[0]

        db_file_name = target + ".db"
        if os.path.exists(db_file_name):
            db = shelve.open(db_file_name)

            report = db.get('report', None)

            if report is not None:
                with open('junit.xml', 'w') as junit_result_file:
                    TestSuite.to_file(junit_result_file, report.test_suites, False, "latin1")



